### ISSUE TITLE
Toronto rebuild

### ISSUE THREAD

**Issue by geografa** [maptime/toronto#1]
Heyo @tristen - I had a fun adventure trying to get the maptime.github.io rebuilt by forking it from starter. I renamed the old maptime.github.io created a new one, but it seemed to break a bunch of repos that depended on it along the way. Seems whichever repo was using starter now needs a rebuild. I think I have most of them up and running but if you're seeing weird empty commits, this is why.

**Comment by tristen** [comment]
I don't understand this issue. A fork is only susceptible to changes from somewhere upstream if you set this up locally. Can you explain what broke?

**Comment by geografa** [comment]
@tristen My original idea was to get the maptime.github.io repo forked from starter. I renamed the **maptime.github.io** repo to **maptime.github.io.old** so I could start a new one forked from starter. Not realizing other repos were sub-pages of this, there were some 404s when hitting the sub-pages. It just takes a rebuild to get them running again (e.g. this trivial commit: https://github.com/maptime/toronto/commit/2ea8931c7c118c5187f1377a95653688e8a1d2d8). Just wanted you to be aware of it.

**Comment by geografa** [comment]
BTW, if there's a better procedure for setting the repo's upstream to a different one, I'd love to know. Do you know if a `git remote set` would've done it?

**Comment by tristen** [comment]
Setting a remote just means you are adding a named reference that points to the path of a git project  to your local git copy so you can sync changes from time to time. `upstream` is a good name as it suggests a repository you forked from. But you can add any number of remotes like 

``` sh
git remote add somearbitraryname repo.git
```
